### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.github.betaflight.BetaflightConfigurator#3]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.
![captura de tela de 2018-02-02 18-26-20](https://user-images.githubusercontent.com/26097419/35753364-999c2fee-0846-11e8-86d5-50690096ecd5.png)

**Comment by LeandroStanger** [comment]
@nedrichards could help

https://www.helicomicro.com/wp-content/uploads/2016/06/betaflight-configurator-01-350x235.jpg
https://www.helicomicro.com/wp-content/uploads/2016/06/betaflight-configurator-02-350x234.jpg
https://www.helicomicro.com/wp-content/uploads/2016/06/betaflight-configurator-03-350x236.jpg
https://www.helicomicro.com/wp-content/uploads/2016/06/betaflight-configurator-04-350x202.jpg

**Comment by alexlarsson** [comment]
Should be better now
